# Generated by Django 4.2.10 on 2024-03-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='preference_level',
            field=models.CharField(choices=[('finalized', 'Finalized'), ('undecided', 'Undecided')], default='undecided', max_length=10),
        ),
    ]
