# Generated by Django 4.2.10 on 2024-03-12 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_schedule_preference_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='preference_level',
            new_name='schedule_status',
        ),
    ]
