# Generated by Django 3.2 on 2024-03-13 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0004_rename_preference_level_schedule_schedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='owner',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='auth.user'),
            preserve_default=False,
        ),
    ]
