# Generated by Django 3.2 on 2024-03-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_calendar_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='status',
            field=models.CharField(choices=[('None', 'None'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='None', max_length=8),
        ),
    ]
