# Generated by Django 3.2 on 2024-03-13 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_remove_contact_status'),
        ('scheduler', '0006_preference_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact'),
        ),
    ]
