# Generated by Django 3.2 on 2024-04-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_remove_contact_status'),
        ('scheduler', '0007_preference_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='contacts',
            field=models.ManyToManyField(to='contacts.Contact'),
        ),
    ]
