# Generated by Django 3.2 on 2024-04-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_remove_contact_status'),
        ('scheduler', '0008_meeting_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='contacts.Contact'),
        ),
    ]
