# Generated by Django 3.2 on 2024-04-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_alter_schedule_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='contacts',
        ),
        migrations.AddField(
            model_name='meeting',
            name='contacts',
            field=models.TextField(blank=True),
        ),
    ]
